### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by naa7** [wnaBee/baseflipper#1]
hey sammy, how are you? I tried to contact you on github but i didn't have any other way other than opening an issue, so that I can get to you. Can you try to see what is my discord username or email from your side if possible? i don't know what my email is for it?

**Comment by wnaBee** [comment]
O shit, how are ya, I can't see your email (discord doesn't support looking at other people's emails) your UN is "Loading..." however. Hope that helps.

Also, talking through issues is tedious going forward, you have any alternative contact options e.g. signal, element, etc.?

**Comment by wnaBee** [comment]
(I'm good by the way, haha)

**Comment by naa7** [comment]
what is your discord name? I think I need new discord :(

**Comment by wnaBee** [comment]
Pec muhn#1809
Shoot me a fr when you get it set up

**Comment by naa7** [comment]
it keeps asking me to verify with phone -_-. i hate this
